version: 2.1

jobs:
  build:
    docker:
      - image: cibuilds/docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build a Docker image"
          command: |
            npm init && \
            docker build -t mfunaki/mynode-container . && \
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin && \
            docker push mfunaki/mynode-container